output-reports:
  active: true
  exclude:
   - 'TxtOutputReport'
   - 'XmlOutputReport'
  # - 'HtmlOutputReport'
   - 'MdOutputReport'
naming:
  EnumNaming:
    active: false
    enumEntryPattern: '[A-Z][_a-zA-Z0-9]*'
style:
  WildcardImport:
    active: true
    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
    excludeImports:
      - 'java.util.*'
      - 'kotlinx.html.*'
