name: Gradle Static Generation, Commit and Push, Deploy Webhook

on:
  push:
    branches: ["master"]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt-openj9'
    - name: Gradle Run
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: run --args='prdWithoutServer'
    - name: Git Commit and Push
      uses: github-actions-x/commit@722d56b8968bf00ced78407bbe2ead81062d8baa
      with:
        github-token: ${{ secrets.GH_PUSH_TOKEN }}
        push-branch: 'master'
        commit-message: 'publish'
        files: deploy
        name: Armando Cordova
        email: jarmandocp@live.com
    - name: HTTP Request Action
      uses: fjogeleit/http-request-action@4cbc7a46b206a7aad09ef774775110b7b94f8523
      with:
        url: ${{ secrets.DEPLOY_WEBHOOK }}
        # Request Method
        method: GET
