name: Deploy Webhook

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: HTTP Request Action
      uses: fjogeleit/http-request-action@4cbc7a46b206a7aad09ef774775110b7b94f8523
      with:
        url: ${{ secrets.DEPLOY_WEBHOOK }}
        method: GET
